#!/usr/bin/env node

// lib/ is generated by scripts/sync-skill-scanner.mjs from the CLI's scanner.
import { scanProject } from './lib/scan.mjs';

try {
  console.log(JSON.stringify(scanProject(process.argv[2] || process.cwd()), null, 2));
} catch (error) {
  console.error(error.message);
  process.exitCode = 2;
}
