import Overview from './reference-cloudscape.jsx';
import React,{useState} from 'react';
import Button from '@cloudscape-design/components/button';
import Input from '@cloudscape-design/components/input';
import Checkbox from '@cloudscape-design/components/checkbox';
import Alert from '@cloudscape-design/components/alert';
import FormField from '@cloudscape-design/components/form-field';
import '@cloudscape-design/global-styles/index.css';
import Select from '@cloudscape-design/components/select';
import RadioGroup from '@cloudscape-design/components/radio-group';
import Toggle from '@cloudscape-design/components/toggle';
import Tabs from '@cloudscape-design/components/tabs';
import Table from '@cloudscape-design/components/table';
import Badge from '@cloudscape-design/components/badge';
import ProgressBar from '@cloudscape-design/components/progress-bar';
import DatePicker from '@cloudscape-design/components/date-picker';
import Pagination from '@cloudscape-design/components/pagination';
import StatusIndicator from '@cloudscape-design/components/status-indicator';
import TokenGroup from '@cloudscape-design/components/token-group';
import {Sheet,mount} from './shared.jsx';
function Preview(){if(new URLSearchParams(location.search).has("overview"))return <Overview/>;const[saved,setSaved]=useState(false),[name,setName]=useState(''),[checked,setChecked]=useState(true);return <Sheet actions={<><Button variant="primary" onClick={()=>setSaved(true)}>保存更改</Button><Button onClick={()=>setSaved(false)}>取消</Button><Button disabled>不可用</Button></>} input={<FormField label="项目名称"><Input value={name} onChange={({detail})=>setName(detail.value)} placeholder="输入项目名称"/></FormField>} selection={<Checkbox checked={checked} onChange={({detail})=>setChecked(detail.checked)}>接收项目通知</Checkbox>} controls={<><Select selectedOption={{value:'design',label:'设计团队'}} options={[{value:'design',label:'设计团队'},{value:'engineering',label:'研发团队'}]}/><RadioGroup value="a" items={[{value:'a',label:'选项 A'},{value:'b',label:'选项 B'}]}/><Toggle checked>开启通知</Toggle></>} navigation={<Tabs tabs={[{id:'overview',label:'概览',content:'项目概览'},{id:'activity',label:'动态',content:'项目动态'},{id:'settings',label:'设置',content:'项目设置'}]}/>} data={<Table variant="embedded" columnDefinitions={[{id:'name',header:'项目',cell:item=>item.name},{id:'status',header:'状态',cell:item=>item.status}]} items={[{name:'Design System',status:'进行中'},{name:'Components',status:'已完成'},{name:'Documentation',status:'待开始'}]}/>} status={<><Badge color="blue">进行中</Badge><Badge color="green">已完成</Badge><Badge color="red">待处理</Badge><div className="overview-progress"><ProgressBar value={50}/></div><div className="overview-progress"><ProgressBar value={100} status="success"/></div></>} extras={<><div><DatePicker value="2026/10/05" placeholder="YYYY/MM/DD"/><TokenGroup items={[{label:'Design'},{label:'Development'},{label:'Documentation'}]}/></div><div><Pagination currentPageIndex={2} pagesCount={5}/><div className="samples"><StatusIndicator type="success">Success</StatusIndicator><StatusIndicator type="error">Error</StatusIndicator><StatusIndicator type="in-progress">In progress</StatusIndicator></div></div></>} feedback={<Alert type={saved?'success':'info'}>{saved?'更改已保存':'所有更改将在确认后保存'}</Alert>}/>;}mount(Preview);
