import Overview from './reference-material.jsx';
import React,{useState} from 'react';
import '@material/web/button/filled-button.js';
import '@material/web/button/outlined-button.js';
import '@material/web/textfield/outlined-text-field.js';
import '@material/web/checkbox/checkbox.js';
import '@material/web/radio/radio.js';
import '@material/web/switch/switch.js';
import '@material/web/slider/slider.js';
import '@material/web/tabs/tabs.js';
import '@material/web/tabs/primary-tab.js';
import '@material/web/chips/chip-set.js';
import '@material/web/chips/assist-chip.js';
import '@material/web/progress/linear-progress.js';
import '@material/web/progress/circular-progress.js';
import '@material/web/button/text-button.js';
import '@material/web/textfield/filled-text-field.js';
import '@material/web/chips/filter-chip.js';
import {Sheet,mount} from './shared.jsx';
function Preview(){if(new URLSearchParams(location.search).has("overview"))return <Overview/>;const[saved,setSaved]=useState(false);return <Sheet actions={<><md-filled-button onClick={()=>setSaved(true)}>保存更改</md-filled-button><md-outlined-button onClick={()=>setSaved(false)}>取消</md-outlined-button><md-filled-button disabled>不可用</md-filled-button></>} input={<md-outlined-text-field label="项目名称" placeholder="输入项目名称" style={{width:'100%'}}/>} selection={<label style={{display:'flex',alignItems:'center',gap:8}}><md-checkbox checked/>接收项目通知</label>} controls={<><div className="samples"><label><md-radio name="choice" value="a" checked/>选项 A</label><label><md-radio name="choice" value="b"/>选项 B</label><md-switch selected aria-label="开启通知"/></div><md-slider value="40" aria-label="进度"/></>} navigation={<md-tabs><md-primary-tab>概览</md-primary-tab><md-primary-tab>动态</md-primary-tab><md-primary-tab>设置</md-primary-tab></md-tabs>} data={<><p className="availability-note">Material Web 未提供表格组件，展示官方 Chip。</p><md-chip-set><md-assist-chip label="Design System"/><md-assist-chip label="Components"/><md-assist-chip label="Documentation"/></md-chip-set></>} status={<><md-linear-progress value="0.5"/><md-linear-progress value="1"/></>} extras={<><div><div className="samples"><md-circular-progress value="0.68"/><md-circular-progress indeterminate/><md-text-button>Text button</md-text-button></div><md-chip-set><md-filter-chip label="Design" selected/><md-filter-chip label="Development"/><md-filter-chip label="Disabled" disabled/></md-chip-set></div><div><md-filled-text-field label="Email address" value="designer@example.com"/><md-outlined-text-field label="Disabled input" disabled/><md-slider value="70" disabled/></div></>} feedback={<p role="status" style={{fontSize:14,margin:0}}>{saved?'✓ 更改已保存':'所有更改将在确认后保存'}</p>}/>;}mount(Preview);
