import avatar from './avatar.svg';
import React from 'react';
import {Avatar,Provider,defaultTheme,Button,ActionButton,Picker,Item,DatePicker,Calendar,RadioGroup,Radio,Checkbox,Switch,Dialog,Heading,Content,ButtonGroup,Text,StatusLight,ProgressBar,ProgressCircle,TableView,TableHeader,Column,TableBody,Row,Cell,Tabs,TabList,TabPanels,Slider,Link,View,TooltipTrigger,Tooltip} from '@adobe/react-spectrum';
import {parseDate} from '@internationalized/date';
import {ReferenceCanvas,listItems} from './reference-layout.jsx';
import {ReferenceIcon,labels,modalText,TourContent,TourPreview} from './reference-content.jsx';
const list=<TableView aria-label="Design system list" width="100%" height={264}><TableHeader><Column>Title</Column><Column>Status</Column></TableHeader><TableBody>{listItems.map(x=><Row key={x.id}><Cell>{x.title}</Cell><Cell>Step 2</Cell></Row>)}</TableBody></TableView>;
const panel=(confirmation=false)=><View backgroundColor="gray-50" borderRadius="medium" padding="size-150" width="100%"><Heading level={4}>{confirmation?'Popconfirm':'Popover Title'}</Heading>{confirmation?<ButtonGroup><Button variant="secondary">Cancel</Button><Button variant="accent">OK</Button></ButtonGroup>:<Text>The floating card popped by clicking.</Text>}</View>;
const tour=(accent=false)=><View backgroundColor={accent?'gray-100':'gray-50'} borderRadius="medium"><TourContent accent={accent} preview={<TourPreview rows={list}/>} link={<Link>Help info ↗</Link>} button={<><Button variant="secondary">Previous</Button><Button variant="accent">Next</Button></>}/></View>;
export default function Overview(){return <Provider theme={defaultTheme} colorScheme="light" locale="en-US"><ReferenceCanvas system="spectrum" slots={{
 buttons:<><Button variant="accent">Primary Button</Button><Button variant="secondary">Default Button</Button><Button variant="negative" style="outline">Danger Button</Button></>,select:<Picker aria-label="Options" defaultSelectedKey="a" width={230}><Item key="a">Option A</Item><Item key="b">Option B</Item></Picker>,date:<DatePicker aria-label="Date" defaultValue={parseDate('2022-11-18')}/>,
 radios:<RadioGroup aria-label="Options" value="2" orientation="horizontal">{labels.map((x,i)=><Radio key={x} value={String(i)} isDisabled={i>2}>{x}</Radio>)}</RadioGroup>,checkboxes:labels.map((x,i)=><Checkbox key={x} isSelected={i===2||i===4} isDisabled={i>2}>{x}</Checkbox>),switches:<div className="ref-stack">{[0,1].map(row=><div className="ref-row" key={row}>{[true,false,true,false].map((x,i)=><Switch key={i} isSelected={x} isDisabled={i>1} aria-label="Switch"/>)}</div>)}</div>,
 modal:<Dialog aria-label="Basic Modal"><Heading>Basic Modal</Heading><Content>{modalText}</Content><ButtonGroup><Button variant="secondary">Cancel</Button><Button variant="accent">OK</Button></ButtonGroup></Dialog>,popover:panel(),popconfirm:panel(true),tooltip:<TooltipTrigger isOpen><ActionButton aria-label="Prompt">?</ActionButton><Tooltip>Prompt Text</Tooltip></TooltipTrigger>,message:<StatusLight variant="positive">This is a normal message</StatusLight>,
 tags:<>{['Tag','+ Tag','Green','Blue','Gold','Red'].map((x,i)=><StatusLight key={x} variant={['neutral','neutral','positive','info','notice','negative'][i]}>{x}</StatusLight>)}</>,alert:<View backgroundColor="positive" padding="size-150" borderRadius="small"><StatusLight variant="positive">Success Text</StatusLight></View>,list,
 progress:<div className="ref-stack"><ProgressBar aria-label="Progress" value={50} width="100%"/><ProgressBar aria-label="Success" value={100} width="100%"/><ProgressBar aria-label="Error" value={70} width="100%"/><div className="ref-row"><ProgressCircle aria-label="Progress 68 percent" value={68} size="L"/><ProgressCircle aria-label="Complete" value={100} size="L"/><ProgressCircle aria-label="Failed" value={100} size="L"/></div><div className="ref-row"><StatusLight variant="info">In Progress</StatusLight><StatusLight variant="positive">Success</StatusLight><StatusLight variant="negative">Failed</StatusLight></div></div>,tour:tour(),tourAccent:tour(true),calendar:<Calendar aria-label="Calendar" defaultValue={parseDate('2022-12-19')}/>,
 avatars:<>{[0,1,2,3,4,5].map(i=><Avatar key={i} src={avatar} alt="User" size="avatar-size-100"/>)}</>,
 tabs:<div className="ref-row">{[0,1].map(i=><Tabs density="compact" aria-label="Tabs" key={i} disabledKeys={['3']}><TabList><Item key="1">Tab1</Item><Item key="2">Tab2</Item><Item key="3">Tab3</Item></TabList><TabPanels><Item key="1"><Content/></Item><Item key="2"><Content/></Item><Item key="3"><Content/></Item></TabPanels></Tabs>)}<Button variant="accent">Dropdown ⌄</Button></div>,sliders:<div className="ref-row"><Slider aria-label="Progress" defaultValue={40} width={170}/><Slider aria-label="Progress" defaultValue={70} width={170}/></div>,badges:<><StatusLight variant="positive">Success</StatusLight><StatusLight variant="negative">Error</StatusLight><StatusLight variant="negative">5</StatusLight></>,floating:<div className="ref-grid">{['?','▤','▤','▤','↑','◷','↑','▤','×'].map((x,i)=><ActionButton key={i} aria-label="Action"><ReferenceIcon index={i}/></ActionButton>)}</div>
}}/></Provider>}
