import React from 'react';
import '@material/web/all.js';
import {ReferenceCanvas,listItems} from './reference-layout.jsx';
import {ReferenceIcon,labels,modalText,TourContent,TourPreview} from './reference-content.jsx';
const list=<md-list>{listItems.map(x=><md-list-item key={x.id}><div slot="headline">{x.title}</div><div slot="supporting-text">{x.description}</div><md-assist-chip slot="end" label="Step 2"/></md-list-item>)}</md-list>;
const surface=(title,children)=><div className="material-reference-surface"><strong>{title}</strong>{children}</div>;
const tour=(accent=false)=><div className={`material-reference-surface ${accent?'material-reference-accent':''}`}><TourContent accent={accent} preview={<TourPreview rows={list}/>} link={<md-text-button>Help info ↗</md-text-button>} button={<><md-outlined-button>Previous</md-outlined-button><md-filled-button>Next</md-filled-button></>}/></div>;
const labeled=(tag,x,i)=><label className="ref-row" key={x}>{React.createElement(tag,{...(tag==='md-switch'?{selected:i%2===0}:(i===2||i===4?{checked:true}:{})),...(i>2?{disabled:true}:{}),'aria-label':x})}{x}</label>;
export default function Overview(){return <ReferenceCanvas system="material" slots={{
 buttons:<><md-filled-button>Primary Button</md-filled-button><md-outlined-button>Default Button</md-outlined-button><md-outlined-button style={{'--md-sys-color-primary':'var(--md-sys-color-error)'}}>Danger Button</md-outlined-button></>,select:<md-outlined-select label=""><md-select-option selected value="a"><div slot="headline">Option A</div></md-select-option><md-select-option value="b"><div slot="headline">Option B</div></md-select-option></md-outlined-select>,
 radios:labels.map((x,i)=>labeled('md-radio',x,i)),checkboxes:labels.map((x,i)=>labeled('md-checkbox',x,i)),switches:<div className="ref-stack">{[0,1].map(row=><div className="ref-row" key={row}>{[0,1,2,3].map(i=><md-switch key={i} {...(i%2===0?{selected:true}:{})} {...(i>1?{disabled:true}:{})} {...(row?{icons:true}:{})} aria-label="Switch"/>)}</div>)}</div>,
 modal:surface('Basic Modal',<><p>{modalText}</p><div className="ref-row" style={{justifyContent:'flex-end'}}><md-text-button>Cancel</md-text-button><md-filled-button>OK</md-filled-button></div></>),popover:surface('Popover Title',<p>The floating card popped by clicking.</p>),popconfirm:surface('Popconfirm',<div className="ref-row"><md-text-button>Cancel</md-text-button><md-filled-button>OK</md-filled-button></div>),
 tags:<md-chip-set>{['Tag','+ Tag','Green','Blue','Gold','Red'].map(x=><md-assist-chip key={x} label={x}/>)}</md-chip-set>,list,
 progress:<div className="ref-stack"><md-linear-progress value="0.5"/><md-linear-progress value="1" style={{'--md-sys-color-primary':'var(--md-sys-color-tertiary)'}}/><md-linear-progress value="0.7" style={{'--md-sys-color-primary':'var(--md-sys-color-error)'}}/><div className="ref-row"><md-circular-progress value="0.68"/><md-circular-progress value="1"/><md-circular-progress value="1" style={{'--md-sys-color-primary':'var(--md-sys-color-error)'}}/></div><md-chip-set><md-assist-chip label="In Progress"/><md-assist-chip label="Success"/><md-assist-chip label="Failed"/></md-chip-set></div>,tour:tour(),tourAccent:tour(true),
 tabs:<div className="ref-row">{[0,1].map(i=><md-tabs key={i}><md-primary-tab>Tab1</md-primary-tab><md-primary-tab>Tab2</md-primary-tab><md-primary-tab disabled>Tab3</md-primary-tab></md-tabs>)}<md-filled-button>Dropdown ⌄</md-filled-button></div>,sliders:<div className="ref-row"><md-slider value="40"/><md-slider value="70"/></div>,floating:<div className="ref-grid">{['?','▤','▤','▤','↑','◷','↑','▤','×'].map((x,i)=>i===8?<md-filled-icon-button key={i}><ReferenceIcon index={i}/></md-filled-icon-button>:<md-outlined-icon-button key={i}><ReferenceIcon index={i}/></md-outlined-icon-button>)}</div>
}}/>}
