import React,{useState} from 'react';
import {FluentProvider,webLightTheme,Button,Dropdown,Option,Input,Radio,Checkbox,Switch,Dialog,DialogSurface,DialogBody,DialogTitle,DialogContent,DialogActions,Popover,PopoverSurface,PopoverTrigger,Tooltip,MessageBar,MessageBarBody,Rating,Tag,Badge,Table,TableBody,TableRow,TableCell,ProgressBar,TabList,Tab,Avatar,Slider,Card,Link,Spinner} from '@fluentui/react-components';
import {Calendar} from '@fluentui/react-calendar-compat';
import {RingExamples} from './reference-fallbacks.jsx';
import {ReferenceCanvas,listItems} from './reference-layout.jsx';
import {ReferenceIcon,labels,modalText,TourContent,TourPreview} from './reference-content.jsx';
const list=<Table><TableBody>{listItems.map(x=><TableRow key={x.id}><TableCell><div className="reference-list-title">{x.title}</div><div className="reference-list-description">{x.description}</div></TableCell><TableCell><Badge appearance="tint" color="brand">Step 2</Badge></TableCell></TableRow>)}</TableBody></Table>;
function Modal(){const[host,setHost]=useState(null);return <div ref={setHost}>{host&&<Dialog open modalType="non-modal"><DialogSurface mountNode={host} backdrop={null}><DialogBody><DialogTitle>Basic Modal</DialogTitle><DialogContent>{modalText}</DialogContent><DialogActions><Button>Cancel</Button><Button appearance="primary">OK</Button></DialogActions></DialogBody></DialogSurface></Dialog>}</div>}
const popup=(confirm=false)=><Popover open inline positioning="below-start"><PopoverTrigger><span/></PopoverTrigger><PopoverSurface>{confirm?<><strong>Popconfirm</strong><div className="ref-row"><Button size="small">Cancel</Button><Button size="small" appearance="primary">OK</Button></div></>:<><strong>Popover Title</strong><p>The floating card popped by clicking.</p></>}</PopoverSurface></Popover>;
const tour=(accent=false)=><Card style={{padding:0}}><TourContent accent={accent} preview={<TourPreview rows={list}/>} link={<Link>Help info ↗</Link>} button={<><Button size="small">Previous</Button><Button size="small" appearance="primary">Next</Button></>}/></Card>;
export default function Overview(){return <FluentProvider theme={webLightTheme}><ReferenceCanvas system="fluent" slots={{
 buttons:<><Button appearance="primary">Primary Button</Button><Button>Default Button</Button><Button>Danger Button</Button></>,select:<Dropdown defaultValue="Option A" defaultSelectedOptions={['a']}><Option value="a">Option A</Option><Option value="b">Option B</Option></Dropdown>,date:<Input type="date" value="2022-11-18"/>,
 radios:labels.map((label,i)=><Radio key={label} label={label} checked={i===2||i===4} disabled={i>2}/>),checkboxes:labels.map((label,i)=><Checkbox key={label} label={label} checked={i===2||i===4} disabled={i>2}/>),switches:<div className="ref-stack">{[0,1].map(row=><div className="ref-row" key={row}>{[true,false,true,false].map((x,i)=><Switch key={i} checked={x} disabled={i>1}/>)}</div>)}</div>,modal:<Modal/>,popover:popup(),popconfirm:popup(true),tooltip:<Tooltip visible content="Prompt Text" relationship="label"><span> </span></Tooltip>,message:<MessageBar intent="success"><MessageBarBody>This is a normal message</MessageBarBody></MessageBar>,
 rating:<Rating value={3.5}/>,tags:<>{['Tag','+ Tag','Green','Blue','Gold','Red'].map((x,i)=><Badge key={x} appearance="tint" color={['subtle','subtle','success','brand','warning','danger'][i]}>{x}</Badge>)}</>,alert:<MessageBar intent="success"><MessageBarBody>Success Text</MessageBarBody></MessageBar>,list,
 progress:<div className="ref-stack"><ProgressBar value={.5}/><ProgressBar value={1} color="success"/><ProgressBar value={.7} color="error"/><RingExamples/><div className="ref-row"><Badge appearance="tint" color="brand">In Progress</Badge><Badge appearance="tint" color="success">Success</Badge><Badge appearance="tint" color="danger">Failed</Badge></div></div>,tour:tour(),tourAccent:tour(true),
 calendar:<Calendar value={new Date(2022,11,19)} showGoToToday={false}/>,
 tabs:<div className="ref-row">{[0,1].map(i=><TabList key={i} defaultSelectedValue="1"><Tab value="1">Tab1</Tab><Tab value="2">Tab2</Tab><Tab value="3" disabled>Tab3</Tab></TabList>)}<Button appearance="primary">Dropdown ⌄</Button></div>,avatars:<>{[false,true].map(square=>['A','U','T'].map(x=><Avatar key={`${square}-${x}`} name={x} shape={square?'square':'circular'} color={x==='U'?'brand':'neutral'}/>))}</>,sliders:<div className="ref-row"><Slider defaultValue={40}/><Slider defaultValue={70}/></div>,badges:<><Badge color="success">Success</Badge><Badge color="danger">Error</Badge><Badge color="danger">5</Badge></>,floating:<div className="ref-grid">{['?','▤','▤','▤','↑','◷','↑','▤','×'].map((x,i)=><Button key={i} shape="circular" appearance={i===8?'primary':'outline'}><ReferenceIcon index={i}/></Button>)}</div>
}}/></FluentProvider>}
