import fs from 'node:fs';
import path from 'node:path';
import { listFiles, pathExists, readJson, toPosix } from './fs-utils.mjs';
import { scanProject } from './scan.mjs';

export const GENERATED_HEADER = '/* Generated by design-workflow tokens. Edit the JSON source, not this file. */';
const EXTENSIONS = ['.tsx', '.ts', '.jsx', '.js', '.mjs', '.cjs', '.css', '.scss', '.less', '.vue', '.svelte'];

export function stripComments(content) {
  return content.replace(/\/\*[\s\S]*?\*\//g, (comment) => comment.replace(/[^\n]/g, ' '))
    .replace(/^\s*\/\/[^\n]*/gm, (comment) => comment.replace(/[^\n]/g, ' '));
}

export function compileTokens(root, settings) {
  const directory = path.join(root, settings.sourceDirectory);
  if (!pathExists(directory)) throw new Error(`Token source directory is missing: ${settings.sourceDirectory}`);
  const nodes = new Map();
  const exported = [];
  const files = listFiles(directory, {excluded:['node_modules','.git']}).filter(file => file.endsWith('.json')).sort();
  if (!files.length) throw new Error(`No JSON token sources found: ${settings.sourceDirectory}`);
  const add = (name, value, cssName, file) => {
    if (nodes.has(name)) throw new Error(`Duplicate token: ${name}`);
    nodes.set(name, {value, file});
    if (cssName) exported.push({name, cssName});
  };
  const walk = (value, segments, file, branch = '') => {
    if (value && typeof value === 'object' && !Array.isArray(value) && !('$value' in value)) {
      for (const [key, child] of Object.entries(value)) {
        if (key.startsWith('$')) continue;
        walk(child, [...segments, key], file, segments.length === 1 ? key : branch);
      }
      return;
    }
    const name = segments.join('.');
    const raw = value && typeof value === 'object' && '$value' in value ? value.$value : value;
    const category = segments[0];
    const parts = segments.slice(1).filter(part => !['primitive','semantic'].includes(part));
    const kebab = (text) => text.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g,'-').toLowerCase();
    let cssName = parts.map(kebab).join('-');
    if (category === 'colors') cssName = `color-${cssName}`;
    if (category === 'typography') cssName = parts.map(kebab).join('-');
    if (!cssName || !/^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(cssName)) throw new Error(`Unsupported CSS token name: ${name}`);
    add(name, raw, branch === 'primitive' ? null : `--${cssName}`, file);
  };
  for (const file of files) {
    const category = path.basename(file, '.json');
    walk(readJson(file), [category], toPosix(path.relative(root,file)));
  }
  const cache = new Map();
  const resolve = (name, active = new Set()) => {
    if (cache.has(name)) return cache.get(name);
    if (active.has(name)) throw new Error(`Cyclic token alias: ${name}`);
    const node = nodes.get(name);
    if (!node) throw new Error(`Unknown token alias: ${name}`);
    if (typeof node.value !== 'string' && typeof node.value !== 'number') throw new Error(`Unsupported token value: ${name}; only string and finite number values are supported.`);
    if (typeof node.value === 'number' && !Number.isFinite(node.value)) throw new Error(`Invalid token number: ${name}`);
    active.add(name);
    const value = String(node.value).replace(/\{([^{}]+)\}/g, (_, reference) => {
      const local = `${name.split('.')[0]}.${reference}`;
      return resolve(nodes.has(reference) ? reference : local, active);
    });
    active.delete(name);
    if (!value.trim() || /[{};\n\r]/.test(value) || /\/\*|\*\//.test(value)) throw new Error(`Unsupported CSS value: ${name}`);
    cache.set(name,value);
    return value;
  };
  const definitions = new Map();
  for (const entry of exported) {
    if (definitions.has(entry.cssName)) throw new Error(`Duplicate CSS token: ${entry.cssName}`);
    definitions.set(entry.cssName, resolve(entry.name));
  }
  // Validate unused primitive aliases too, so latent source errors do not survive export.
  for (const name of nodes.keys()) resolve(name);
  if (!definitions.size) throw new Error('No exportable tokens found.');
  const css = `${GENERATED_HEADER}\n:root {\n${[...definitions].sort(([a],[b])=>a.localeCompare(b)).map(([name,value])=>`  ${name}: ${value};`).join('\n')}\n}\n`;
  return {css, definitions, sourceFiles:files.map(file=>toPosix(path.relative(root,file)))};
}

function resolveImport(from, reference) {
  if (!reference.startsWith('.')) return null;
  const base = path.resolve(path.dirname(from), reference.split(/[?#]/)[0]);
  for (const file of [base,...EXTENSIONS.map(ext=>base+ext),...EXTENSIONS.map(ext=>path.join(base,`index${ext}`))]) {
    if (pathExists(file) && fs.statSync(file).isFile()) return file;
  }
  return null;
}

export function reachableFiles(root, entry) {
  const visited = new Set();
  const pending = [path.join(root,entry)];
  const unresolved = [];
  while (pending.length) {
    const file = pending.pop();
    if (visited.has(file)) continue;
    if (!pathExists(file)) { unresolved.push(file); continue; }
    visited.add(file);
    const content = stripComments(fs.readFileSync(file,'utf8'));
    const references = [...content.matchAll(/\b(?:import|export)\s+(?:[^;'"\n]*?\s+from\s*)?['"]([^'"]+)['"]|@import\s+(?:url\(\s*)?['"]([^'"]+)['"]/g)];
    for (const match of references) {
      const reference = match[1] || match[2];
      if (!reference.startsWith('.')) continue;
      const resolved = resolveImport(file,reference);
      if (resolved) pending.push(resolved);
      else unresolved.push(`${file}: ${reference}`);
    }
  }
  return {visited, unresolved};
}

export function buildTokens(target, {force = false} = {}) {
  const scan = scanProject(target);
  const settings = scan.config.tokens;
  if (!settings || settings.mode !== 'managed') throw new Error('Configure tokens.mode="managed", sourceDirectory, outputFile and entryFiles before exporting. Existing toolchains can use mode="external".');
  const result = compileTokens(scan.root,settings);
  const output = path.join(scan.root,settings.outputFile);
  if (pathExists(output) && !fs.readFileSync(output,'utf8').startsWith(GENERATED_HEADER) && !force) {
    throw new Error(`Refusing to replace an unmanaged file: ${settings.outputFile}. Select a new outputFile or explicitly use --force.`);
  }
  fs.mkdirSync(path.dirname(output),{recursive:true});
  fs.writeFileSync(output,result.css);
  return {root:scan.root,outputFile:settings.outputFile,sourceFiles:result.sourceFiles,tokenCount:result.definitions.size,entryFiles:settings.entryFiles,integration:'Import the output CSS from every configured runtime entry, directly or through relative static imports. check reports missing integration; this command does not edit business code.'};
}

export function checkTokens(scan) {
  const settings = scan.config.tokens;
  if (!settings) return {status:'unconfigured',scope:'Configure managed JSON export or external CSS definition mapping to check token integration.',issues:[]};
  const {root} = scan;
  const issues = [];
  const issue = (type,file,message,severity='P1', extra={}) => issues.push({type,file,message,severity,...extra});
  const definitionFiles = settings.mode === 'managed' ? [settings.outputFile] : settings.definitionFiles;
  const names = new Set(settings.externalTokens || []);
  if (settings.mode === 'managed') {
    try {
      const compiled = compileTokens(root,settings);
      for (const name of compiled.definitions.keys()) names.add(name);
      const output = path.join(root,settings.outputFile);
      if (!pathExists(output)) issue('missing-token-output',settings.outputFile,'Run design-workflow tokens to create the runtime CSS.');
      else if (fs.readFileSync(output,'utf8') !== compiled.css) issue('token-output-drift',settings.outputFile,'Runtime CSS differs from the JSON source. Review and regenerate tokens.');
    } catch (error) {issue('invalid-token-source',settings.sourceDirectory,error.message);}
  }
  for (const file of definitionFiles) {
    if (!pathExists(path.join(root,file))) {
      if (settings.mode === 'external') issue('missing-token-definitions',file,'Configured CSS token definition file is missing.');
      continue;
    }
    if (settings.mode === 'external') {
      const content = stripComments(fs.readFileSync(path.join(root,file),'utf8'));
      for (const match of content.matchAll(/(--[a-zA-Z0-9_-]+)\s*:/g)) names.add(match[1]);
    }
  }
  const reachable = new Set();
  for (const entry of settings.entryFiles) {
    if (!pathExists(path.join(root,entry))) {issue('missing-token-entry',entry,'Configured runtime entry is missing.');continue;}
    const graph = reachableFiles(root,entry);
    for (const file of graph.visited) reachable.add(file);
    if (!definitionFiles.some(file=>graph.visited.has(path.join(root,file)))) issue('token-integration-unverified',entry,'No configured token CSS file is reachable through relative static imports. Aliases, dynamic imports and framework-injected styles need separate verification.','P2');
    if (graph.unresolved.length) issue('token-import-unresolved',entry,'Some relative imports could not be resolved; integration coverage is incomplete.','P2',{imports:graph.unresolved});
  }
  const sources = new Set([...reachable, ...scan.sourceRoots.flatMap(dir=>listFiles(path.join(root,dir),{excluded:['node_modules','dist','build','.next','coverage','.git']}))]);
  for (const file of definitionFiles) if (pathExists(path.join(root,file))) sources.add(path.join(root,file));
  for (const file of sources) {
    if (!EXTENSIONS.includes(path.extname(file))) continue;
    const content = stripComments(fs.readFileSync(file,'utf8'));
    const localNames = new Set([...content.matchAll(/(--[a-zA-Z0-9_-]+)\s*:/g)].map(match=>match[1]));
    for (const match of content.matchAll(/var\(\s*(--[a-zA-Z0-9_-]+)\s*([,)])/g)) {
      if (names.has(match[1]) || localNames.has(match[1])) continue;
      const fallback = match[2] === ',';
      issue('unmapped-token-reference',toPosix(path.relative(root,file)),`CSS variable ${match[1]} is absent from the configured token mapping${fallback ? '; a fallback is present' : ''}. Review local declarations or external definitions.`,fallback?'P2':'P1',{value:match[1],line:content.slice(0,match.index).split('\n').length});
    }
  }
  return {status:issues.length?'issues-found':'static-checks-passed',scope:'Static CSS token mapping and relative-import reachability only. Scope, computed styles, dynamic code and browser behavior remain unverified.',issues};
}
